version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     ports:
       - "3306:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     container_name: leantime
     volumes:
       - config_data:/var/www/html/config
       - public_userfiles_data:/var/www/html/public/userfiles
       - userfiles_data:/var/www/html/userfiles
       - logs_data:/var/www/html/resources/logs
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
     ports:
       - "9000:9000"
       - "80:80"
     depends_on:
       - db
volumes:
    db_data: {}
    config_data: {}
    public_userfiles_data: {}
    userfiles_data: {}
    logs_data: {}
